<?php
/**
 * @var array $errors
 */

?>
<h1>login</h1>


<form method="post">
    <div>
        Username: <input type="text" name="login" />
        <div>
            <?php if ($errors['login'] ?? ''): ?>
                <span class="error"><?= $errors['login'] ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div>
        Password: <input type="password" name="pass" />
        <div>
            <?php if ($errors['pass'] ?? ''): ?>
                <span class="error"><?= $errors['pass'] ?></span>
            <?php endif; ?>
        </div>
    </div>
    <input type="submit" name="submit" value="login" />
</form>

<?php if ($errors['session'] ?? ''): ?>
    <span class="error"><?= $errors['session'] ?></span>
<?php endif ?>
