<?php
/**
 * @var array $task
 */

?>

<?php if ($_SESSION['is_login'] ?? ''): ?>
    <?php include "admin_task_view.phtml"; ?>
<?php else: ?>
    <div class="task">
        <div>name: <?= $task['name'] ?></div>
        <div>email: <?= $task['email'] ?></div>
        <div>text: <?= html_entity_decode($task['text']) ?></div>
        <div>is completed: <?php echo $task['is_completed'] ? 'yes' : 'no' ?></div>
        <?php if($task['is_edited'] ?? ''): ?>
            <div>edited by admin </div>
        <?php endif; ?>
    </div>
<?php endif; ?>